# Pages 项目配置
name = "pairusuo"
pages_build_output_dir = "out"
compatibility_date = "2024-10-01"  
compatibility_flags = ["nodejs_compat"]

# R2 绑定（如果需要在 Functions 中直接访问）
[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "pairusuo-top"