# Wrangler 配置文件
name = "pairusuo"
compatibility_date = "2024-10-01"
compatibility_flags = ["nodejs_compat"]

# Pages 项目配置
[env.production]
# 生产环境变量在 CF Dashboard 中配置

[env.preview] 
# 预览环境变量

# R2 绑定（如果需要在 Functions 中直接访问）
[[env.production.r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "pairusuo-top"

[[env.preview.r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "pairusuo-top"