name = "pairusuo-blog"
compatibility_date = "2025-08-31"
pages_build_output_dir = "out"

[env.preview]
name = "pairusuo-blog-preview"

[env.preview.vars]
NEXT_PUBLIC_SITE_URL = "https://pairusuo-blog-preview.pages.dev"
NEXT_PUBLIC_SITE_NAME = "派入所 Preview"

[env.production]
name = "pairusuo-blog"

[env.production.vars]
NEXT_PUBLIC_SITE_URL = "https://pairusuo.top"
NEXT_PUBLIC_SITE_NAME = "派入所"

# 可选的社交媒体配置
# NEXT_PUBLIC_TWITTER_HANDLE = "@pairusuo"
# NEXT_PUBLIC_GITHUB_URL = "https://github.com/pairusuo"
# NEXT_PUBLIC_EMAIL = "dirkchoumvp@gmail.com"

# Cloudflare R2 配置
# R2_ACCOUNT_ID = "ea56e190e74f8a0bccb4796a7f743106"
# R2_ACCESS_KEY_ID = "447245a88df7a5b479dfd0b7fb931f60"
# R2_SECRET_ACCESS_KEY = "906bde863a648550098c4d3bee5f897231863cf4a68cb4dba5fc2c7506d2963a"
# R2_BUCKET_NAME = "pairusuo-top"
# R2_PUBLIC_URL = "https://image.pairusuo.top"